### ISSUE TITLE
Support for Nutmeg?

### ISSUE THREAD

**Issue by sambapete** [hastexo/tutor-contrib-s3#55]
I know it's more a question than a bug, but is there a timeline for support of the Nutmeg release?

**Comment by fghaas** [comment]
Hi Pierre, we'll hopefully have Nutmeg support in all our plugins by the end of the month. It's somewhat slow going because it's all-or-nothing and there's no backward compatibility, because Tutor [switched from `lms.env.json` to `lms.yml` (etc.) in version 14](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#v1400-2022-06-09) and there's no way (that we know of) for a plugin to support both. So users will need Nutmeg support in _all_ plugins that they use, at the same time, which basically means that we'll have to add Nutmeg support to all our plugins and then release Nutmeg-supporting versions simultaneously, within a day or so.

I believe issues like these will creep up around most major releases in the future, complicated by the fact that it's been [made very clear](https://github.com/overhangio/tutor/pull/686#issuecomment-1173541872) that only one Open edX release (and hence, one Tutor major release) will be supported by Tutor at any one time. For people like yourself who, if i understand correctly, have historically adopted every other Open edX major release (skipping the one in between), this is probably going to be a source of pain, sadly.

**Comment by sambapete** [comment]
Sorry Florian, I forgot to reply yesterday after seeing your answer.

As I am part of the Build Test Release working group for Open edX, I am fully aware of the changes involved by the changes made to Tutor plugins. 

As for only one supported Open edX release at a time, that was always the case even with the Native installation. We must rely on the community to help people with previous releases.

We are still running Koa with Native in our Production environment. We simply could not adopt Tutor yet because of issues between our payment processor and the Payment MFE who didn't support it. As we are soon switching to one of the supported payment processor, we will be able to migrate from Koa to Lilac to Maple and Nutmeg by the end of the year. Most probably before November and way before Olive is released in December.

Telling me your plugins will be supporting Nutmeg hopefully by the end of the month is fine with me. As we have relied on S3 until now, I would prefer to use S3 and your plugin instead of relying on storage on the local filesystem or even Minio. I've been exploring all potential solutions with our Nutmeg test server right now.

Thanks!

**Comment by fghaas** [comment]
If this plugin is the only one you're planning to use, you are certainly most welcome to test with the topic branch from PR #56 ahead of us cutting a release. :)

**Comment by sambapete** [comment]
I might just do that in the coming days or next week :)

**Comment by fghaas** [comment]
Just wanted to add another thought here:

> As for only one supported Open edX release at a time, that was always the case even with the Native installation. We must rely on the community to help people with previous releases.

Yes, I am aware of that, but at least there were *branches* in edx-configuration for each Open edX named release. You could submit PRs for those, and if you made a good enough case you could get bug fixes and even some minor feature backports into those even if the next release had already dropped. For Tutor there's `master` and there's `nightly` and there's "run your own fork", which by extension means plugin authors *also* have no incentive to even create branches that match an Open edX named release (or a Tutor major release). I'm concerned that we're probably ending up a worse situation (as regards forks) than we ever had with the Ansible based installation.

And, as my colleague @foadlind recently pointed out quite correctly, if everyone is incentivized to run their own Tutor forks anyway, what's the upside of going to the trouble of maintaining a plugin?

**Comment by foadlind** [comment]
#56 is now merged and we have cut a new release (v1.0.0), the plugin now supports Tutor14 and Open edX Nutmeg. :tada:
